Gemfile
Gemfile.lock
app/models/user.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20220829185753_devise_create_users.rb
db/migrate/20220829191740_add_first_name_and_last_name_to_users.rb
db/schema.rb
test/models/user_test.rb

Generated Users Table and added first_name and last_name

Generated Users Table

---

app/controllers/vehicles_controller.rb
app/views/vehicles/index.html.erb

Vehicles now has and index

---

app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb

added views folders

---

app/controllers/vehicles_controller.rb
app/views/vehicles/edit.html.erb

Created edit and update models
Created simple form to update vehicle

edit added to controllers

---

app/assets/stylesheets/application.scss
app/controllers/maintenances_controller.rb
app/controllers/problems_controller.rb
app/controllers/wishlists_controller.rb
app/views/maintenances/edit.html.erb
app/views/maintenances/index.html.erb
app/views/maintenances/new.html.erb
app/views/maintenances/show.html.erb
app/views/problems/edit.html.erb
app/views/problems/index.html.erb
app/views/problems/new.html.erb
app/views/problems/show.html.erb
app/views/wishlists/edit.html.erb
app/views/wishlists/index.html.erb
app/views/wishlists/new.html.erb
app/views/wishlists/show.html.erb

Wishlist, Problems, Maintenences controlleres methods done

---

Gemfile.lock
app/views/problems/show.html.erb

Modal for edit and delete

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar-footer.scss
app/assets/stylesheets/pages/_index.scss
app/views/layouts/application.html.erb
app/views/problems/index.html.erb
app/views/shared/_bottom_navbar.html.erb

Navbar partial. No Profile to link to yet

Bottom navbar partial

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards_show.scss
app/views/vehicles/index.html.erb
app/views/wishlists/show.html.erb

ParcialCard

---

app/assets/stylesheets/components/_cards_show.scss
app/assets/stylesheets/components/_navbar-footer.scss
app/assets/stylesheets/pages/_global.scss
app/views/shared/_bottom_navbar.html.erb
app/views/vehicles/index.html.erb

fixed most index and navbar

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_small-overview-cards.scss
app/controllers/vehicles_controller.rb
app/javascript/application.js
app/views/vehicles/show.html.erb
package.json
yarn.lock

Charts and Overview page (Vehicle/Show) done!

charts done

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_global.scss
app/assets/stylesheets/pages/_maintenance_new.scss
app/assets/stylesheets/pages/_problems_edit.scss
app/assets/stylesheets/pages/_problems_new.scss
app/views/maintenances/edit.html.erb
app/views/maintenances/new.html.erb
app/views/problems/edit.html.erb
app/views/problems/new.html.erb
app/views/wishlists/edit.html.erb
app/views/wishlists/new.html.erb

styled forms

---

app/views/overview/index.html.erb

Created overview Index

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_carousel.scss
app/views/pages/home.html.erb

Still need to finish the homepage

need to fix the rest of homepage

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/views/pages/home.html.erb
config/routes.rb

fixed the login button

---

app/controllers/maintenances_controller.rb
app/views/vehicles/show.html.erb
db/seeds.rb

now show last done at if the task has been done before

---

app/assets/stylesheets/pages/_global.scss
app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/layouts/application.html.erb

Not exactly the same design as the other pages but doesn't really need to be.

Overview design

---

app/assets/stylesheets/components/_small-overview-cards.scss
app/views/vehicles/show.html.erb

Working on matching styles on the Vehicles Overview Page
Tab overview:
- Created white cards to match other tabs but no border radius
- Standardized headers across tabs
- Standardized add button across tabs

styling vehicles show

---

app/assets/stylesheets/pages/_vehicles_show.scss
app/models/maintenance.rb
app/models/problem.rb
app/models/wishlist.rb
app/views/vehicles/show.html.erb

fixed the long url bug and made it so price forms cant go negative

fixed the long url bug and made it so forms cant go negative

---

app/assets/stylesheets/components/_overview-header.scss
app/assets/stylesheets/components/_overview_boxes.scss
app/assets/stylesheets/components/_small-overview-cards.scss
app/views/overview/index.html.erb

front-end done

---

app/assets/stylesheets/pages/_index.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/vehicles/new.html.erb

sign up fixed

---

app/assets/stylesheets/pages/_vehicles_show.scss
app/views/devise/registrations/edit.html.erb
app/views/vehicles/new.html.erb
app/views/vehicles/show.html.erb

Styled and added placeholders to add vehicle page. Put shadow on wishlist, maintanence lists

Styled add vehicle, and maintanence, wishlist

---

app/assets/stylesheets/components/_cards_show.scss
app/views/vehicles/show.html.erb

vehicles cards + bug fix

---

app/models/maintenance.rb
app/models/problem.rb
app/models/vehicle.rb
app/models/wishlist.rb

did all the validations

---

app/assets/stylesheets/pages/_vehicles_show.scss
app/views/vehicles/show.html.erb

small style changes

---

app/assets/stylesheets/components/_navbar-footer.scss
app/views/shared/_bottom_navbar.html.erb

nav bar bottoms action color added

---

app/assets/stylesheets/pages/_login_page.scss
app/controllers/application_controller.rb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

Login page
